# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.29.6/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.29.6/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/lucian/Documents/GitHub/Blokus2/Blokus

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/lucian/Documents/GitHub/Blokus2/Blokus

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.29.6/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.29.6/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/lucian/Documents/GitHub/Blokus2/Blokus/CMakeFiles /Users/lucian/Documents/GitHub/Blokus2/Blokus//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/lucian/Documents/GitHub/Blokus2/Blokus/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Blokus

# Build rule for target.
Blokus: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Blokus
.PHONY : Blokus

# fast build rule for target.
Blokus/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Blokus.dir/build.make CMakeFiles/Blokus.dir/build
.PHONY : Blokus/fast

Board.o: Board.cpp.o
.PHONY : Board.o

# target to build an object file
Board.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Blokus.dir/build.make CMakeFiles/Blokus.dir/Board.cpp.o
.PHONY : Board.cpp.o

Board.i: Board.cpp.i
.PHONY : Board.i

# target to preprocess a source file
Board.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Blokus.dir/build.make CMakeFiles/Blokus.dir/Board.cpp.i
.PHONY : Board.cpp.i

Board.s: Board.cpp.s
.PHONY : Board.s

# target to generate assembly for a file
Board.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Blokus.dir/build.make CMakeFiles/Blokus.dir/Board.cpp.s
.PHONY : Board.cpp.s

Cell.o: Cell.cpp.o
.PHONY : Cell.o

# target to build an object file
Cell.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Blokus.dir/build.make CMakeFiles/Blokus.dir/Cell.cpp.o
.PHONY : Cell.cpp.o

Cell.i: Cell.cpp.i
.PHONY : Cell.i

# target to preprocess a source file
Cell.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Blokus.dir/build.make CMakeFiles/Blokus.dir/Cell.cpp.i
.PHONY : Cell.cpp.i

Cell.s: Cell.cpp.s
.PHONY : Cell.s

# target to generate assembly for a file
Cell.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Blokus.dir/build.make CMakeFiles/Blokus.dir/Cell.cpp.s
.PHONY : Cell.cpp.s

Clock.o: Clock.cpp.o
.PHONY : Clock.o

# target to build an object file
Clock.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Blokus.dir/build.make CMakeFiles/Blokus.dir/Clock.cpp.o
.PHONY : Clock.cpp.o

Clock.i: Clock.cpp.i
.PHONY : Clock.i

# target to preprocess a source file
Clock.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Blokus.dir/build.make CMakeFiles/Blokus.dir/Clock.cpp.i
.PHONY : Clock.cpp.i

Clock.s: Clock.cpp.s
.PHONY : Clock.s

# target to generate assembly for a file
Clock.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Blokus.dir/build.make CMakeFiles/Blokus.dir/Clock.cpp.s
.PHONY : Clock.cpp.s

Commands.o: Commands.cpp.o
.PHONY : Commands.o

# target to build an object file
Commands.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Blokus.dir/build.make CMakeFiles/Blokus.dir/Commands.cpp.o
.PHONY : Commands.cpp.o

Commands.i: Commands.cpp.i
.PHONY : Commands.i

# target to preprocess a source file
Commands.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Blokus.dir/build.make CMakeFiles/Blokus.dir/Commands.cpp.i
.PHONY : Commands.cpp.i

Commands.s: Commands.cpp.s
.PHONY : Commands.s

# target to generate assembly for a file
Commands.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Blokus.dir/build.make CMakeFiles/Blokus.dir/Commands.cpp.s
.PHONY : Commands.cpp.s

Move.o: Move.cpp.o
.PHONY : Move.o

# target to build an object file
Move.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Blokus.dir/build.make CMakeFiles/Blokus.dir/Move.cpp.o
.PHONY : Move.cpp.o

Move.i: Move.cpp.i
.PHONY : Move.i

# target to preprocess a source file
Move.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Blokus.dir/build.make CMakeFiles/Blokus.dir/Move.cpp.i
.PHONY : Move.cpp.i

Move.s: Move.cpp.s
.PHONY : Move.s

# target to generate assembly for a file
Move.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Blokus.dir/build.make CMakeFiles/Blokus.dir/Move.cpp.s
.PHONY : Move.cpp.s

Piece.o: Piece.cpp.o
.PHONY : Piece.o

# target to build an object file
Piece.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Blokus.dir/build.make CMakeFiles/Blokus.dir/Piece.cpp.o
.PHONY : Piece.cpp.o

Piece.i: Piece.cpp.i
.PHONY : Piece.i

# target to preprocess a source file
Piece.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Blokus.dir/build.make CMakeFiles/Blokus.dir/Piece.cpp.i
.PHONY : Piece.cpp.i

Piece.s: Piece.cpp.s
.PHONY : Piece.s

# target to generate assembly for a file
Piece.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Blokus.dir/build.make CMakeFiles/Blokus.dir/Piece.cpp.s
.PHONY : Piece.cpp.s

PieceSet.o: PieceSet.cpp.o
.PHONY : PieceSet.o

# target to build an object file
PieceSet.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Blokus.dir/build.make CMakeFiles/Blokus.dir/PieceSet.cpp.o
.PHONY : PieceSet.cpp.o

PieceSet.i: PieceSet.cpp.i
.PHONY : PieceSet.i

# target to preprocess a source file
PieceSet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Blokus.dir/build.make CMakeFiles/Blokus.dir/PieceSet.cpp.i
.PHONY : PieceSet.cpp.i

PieceSet.s: PieceSet.cpp.s
.PHONY : PieceSet.s

# target to generate assembly for a file
PieceSet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Blokus.dir/build.make CMakeFiles/Blokus.dir/PieceSet.cpp.s
.PHONY : PieceSet.cpp.s

RandomMoveGen.o: RandomMoveGen.cpp.o
.PHONY : RandomMoveGen.o

# target to build an object file
RandomMoveGen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Blokus.dir/build.make CMakeFiles/Blokus.dir/RandomMoveGen.cpp.o
.PHONY : RandomMoveGen.cpp.o

RandomMoveGen.i: RandomMoveGen.cpp.i
.PHONY : RandomMoveGen.i

# target to preprocess a source file
RandomMoveGen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Blokus.dir/build.make CMakeFiles/Blokus.dir/RandomMoveGen.cpp.i
.PHONY : RandomMoveGen.cpp.i

RandomMoveGen.s: RandomMoveGen.cpp.s
.PHONY : RandomMoveGen.s

# target to generate assembly for a file
RandomMoveGen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Blokus.dir/build.make CMakeFiles/Blokus.dir/RandomMoveGen.cpp.s
.PHONY : RandomMoveGen.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Blokus.dir/build.make CMakeFiles/Blokus.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Blokus.dir/build.make CMakeFiles/Blokus.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Blokus.dir/build.make CMakeFiles/Blokus.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Blokus"
	@echo "... Board.o"
	@echo "... Board.i"
	@echo "... Board.s"
	@echo "... Cell.o"
	@echo "... Cell.i"
	@echo "... Cell.s"
	@echo "... Clock.o"
	@echo "... Clock.i"
	@echo "... Clock.s"
	@echo "... Commands.o"
	@echo "... Commands.i"
	@echo "... Commands.s"
	@echo "... Move.o"
	@echo "... Move.i"
	@echo "... Move.s"
	@echo "... Piece.o"
	@echo "... Piece.i"
	@echo "... Piece.s"
	@echo "... PieceSet.o"
	@echo "... PieceSet.i"
	@echo "... PieceSet.s"
	@echo "... RandomMoveGen.o"
	@echo "... RandomMoveGen.i"
	@echo "... RandomMoveGen.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

